#!/bin/bash

# 显示项目开发规则
# 使用方法: ./scripts/show-rules.sh

echo ""
echo "=========================================="
echo "📖 项目开发规则"
echo "=========================================="
echo ""
echo "⚠️  重要提醒："
echo ""
echo "1. 所有开发记录必须写入 CHANGELOG.md"
echo "2. 禁止创建新的独立 .md 文件"
echo "3. 遵守 Git 提交规范"
echo "4. 完成功能后立即更新文档"
echo ""
echo "=========================================="
echo "📚 核心文档"
echo "=========================================="
echo ""
echo "• README.md           - 项目介绍"
echo "• 项目说明.md         - 详细说明"
echo "• CHANGELOG.md        - 开发日志（最重要）"
echo "• .project-rules.md   - 开发规则（必读）"
echo "• 开发必读.md         - 快速入门"
echo ""
echo "=========================================="
echo "🔍 快速命令"
echo "=========================================="
echo ""
echo "查看开发日志:"
echo "  cat CHANGELOG.md | less"
echo ""
echo "查看最近10条更新:"
echo "  head -n 100 CHANGELOG.md"
echo ""
echo "搜索功能记录:"
echo "  grep '功能关键词' CHANGELOG.md"
echo ""
echo "=========================================="
echo ""


