-- 创建销售发票表
CREATE TABLE sales_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES companies(id),
    buyer_id BIGINT NOT NULL REFERENCES companies(id),
    seller_name VARCHAR(255) NOT NULL,
    buyer_name VARCHAR(255) NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL CHECK (total_amount >= 0),
    invoice_date DATE NOT NULL,
    invoice_number VARCHAR(100),
    invoice_url TEXT,
    invoice_file_name VARCHAR(255),
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),

    -- 索引
    CONSTRAINT sales_invoices_seller_buyer_date_unique UNIQUE(seller_id, buyer_id, invoice_date, invoice_number)
);

-- 创建进项发票表
CREATE TABLE purchase_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL REFERENCES companies(id),
    buyer_id BIGINT NOT NULL REFERENCES companies(id),
    seller_name VARCHAR(255) NOT NULL,
    buyer_name VARCHAR(255) NOT NULL,
    payment_amount DECIMAL(15,2) NOT NULL CHECK (payment_amount >= 0),
    payment_date DATE NOT NULL,
    invoice_type VARCHAR(20) NOT NULL CHECK (invoice_type IN ('专票', '普票', '其他')),
    invoice_number VARCHAR(100),
    invoice_issued BOOLEAN DEFAULT FALSE,
    invoice_url TEXT,
    invoice_file_name VARCHAR(255),
    payment_voucher_url TEXT,
    payment_voucher_file_name VARCHAR(255),
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),

    -- 索引
    CONSTRAINT purchase_invoices_seller_buyer_date_unique UNIQUE(seller_id, buyer_id, payment_date, invoice_number)
);

-- 创建销售发票文件表（用于文件版本管理）
CREATE TABLE sales_invoice_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100),
    storage_bucket VARCHAR(100) DEFAULT 'invoices',
    storage_path TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    uploaded_by UUID REFERENCES auth.users(id)
);

-- 创建进项发票文件表（用于文件版本管理）
CREATE TABLE purchase_invoice_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES purchase_invoices(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100),
    file_type VARCHAR(20) NOT NULL CHECK (file_type IN ('invoice', 'payment_voucher')),
    storage_bucket VARCHAR(100) DEFAULT 'invoices',
    storage_path TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT NOW(),
    uploaded_by UUID REFERENCES auth.users(id)
);

-- 创建索引
CREATE INDEX idx_sales_invoices_seller_id ON sales_invoices(seller_id);
CREATE INDEX idx_sales_invoices_buyer_id ON sales_invoices(buyer_id);
CREATE INDEX idx_sales_invoices_date ON sales_invoices(invoice_date);
CREATE INDEX idx_sales_invoices_created_at ON sales_invoices(created_at);
CREATE INDEX idx_sales_invoices_amount ON sales_invoices(total_amount);

CREATE INDEX idx_purchase_invoices_seller_id ON purchase_invoices(seller_id);
CREATE INDEX idx_purchase_invoices_buyer_id ON purchase_invoices(buyer_id);
CREATE INDEX idx_purchase_invoices_date ON purchase_invoices(payment_date);
CREATE INDEX idx_purchase_invoices_created_at ON purchase_invoices(created_at);
CREATE INDEX idx_purchase_invoices_amount ON purchase_invoices(payment_amount);
CREATE INDEX idx_purchase_invoices_issued ON purchase_invoices(invoice_issued);

-- 创建更新时间戳的函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 创建触发器自动更新 updated_at
CREATE TRIGGER update_sales_invoices_updated_at
    BEFORE UPDATE ON sales_invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_purchase_invoices_updated_at
    BEFORE UPDATE ON purchase_invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 启用行级安全策略
ALTER TABLE sales_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales_invoice_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_invoice_files ENABLE ROW LEVEL SECURITY;

-- 创建RLS策略

-- 销售发票策略
CREATE POLICY "Users can view sales invoices for their companies" ON sales_invoices
    FOR SELECT USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can insert sales invoices for their companies" ON sales_invoices
    FOR INSERT WITH CHECK (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can update sales invoices for their companies" ON sales_invoices
    FOR UPDATE USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can delete sales invoices for their companies" ON sales_invoices
    FOR DELETE USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

-- 进项发票策略
CREATE POLICY "Users can view purchase invoices for their companies" ON purchase_invoices
    FOR SELECT USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can insert purchase invoices for their companies" ON purchase_invoices
    FOR INSERT WITH CHECK (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can update purchase invoices for their companies" ON purchase_invoices
    FOR UPDATE USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can delete purchase invoices for their companies" ON purchase_invoices
    FOR DELETE USING (
        seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
        buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid())
    );

-- 文件表策略
CREATE POLICY "Users can view invoice files for their invoices" ON sales_invoice_files
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM sales_invoices si
            WHERE si.id = sales_invoice_files.invoice_id
            AND (si.seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
                 si.buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()))
        )
    );

CREATE POLICY "Users can manage invoice files for their invoices" ON sales_invoice_files
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM sales_invoices si
            WHERE si.id = sales_invoice_files.invoice_id
            AND (si.seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
                 si.buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()))
        )
    );

CREATE POLICY "Users can view purchase invoice files for their invoices" ON purchase_invoice_files
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM purchase_invoices pi
            WHERE pi.id = purchase_invoice_files.invoice_id
            AND (pi.seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
                 pi.buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()))
        )
    );

CREATE POLICY "Users can manage purchase invoice files for their invoices" ON purchase_invoice_files
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM purchase_invoices pi
            WHERE pi.id = purchase_invoice_files.invoice_id
            AND (pi.seller_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()) OR
                 pi.buyer_id IN (SELECT company_id FROM user_companies WHERE user_id = auth.uid()))
        )
    );