-- Migration: Create profit_calculations and custom_fees tables for freight fee management
-- Created by: Supabase CLI
-- Date: 2025-11-20 02:19:55

-- Create profit_calculations table
CREATE TABLE IF NOT EXISTS profit_calculations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
  sale_total DECIMAL(15,2) NOT NULL DEFAULT 0,
  purchase_total DECIMAL(15,2) NOT NULL DEFAULT 0,
  taxable_purchase_total DECIMAL(15,2) NOT NULL DEFAULT 0,
  calculated_tax_fee DECIMAL(15,2) NOT NULL DEFAULT 0,
  freight_fee DECIMAL(15,2) NOT NULL DEFAULT 0,
  estimated_profit DECIMAL(15,2) NOT NULL DEFAULT 0,
  profit_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create custom_fees table
CREATE TABLE IF NOT EXISTS custom_fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,
  label VARCHAR(100) NOT NULL,
  amount DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_profit_calculations_inquiry_id ON profit_calculations(inquiry_id);
CREATE INDEX IF NOT EXISTS idx_custom_fees_inquiry_id ON custom_fees(inquiry_id);

-- Create update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for automatic timestamp updates
DROP TRIGGER IF EXISTS update_profit_calculations_updated_at ON profit_calculations;
CREATE TRIGGER update_profit_calculations_updated_at
    BEFORE UPDATE ON profit_calculations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_custom_fees_updated_at ON custom_fees;
CREATE TRIGGER update_custom_fees_updated_at
    BEFORE UPDATE ON custom_fees
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE profit_calculations ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_fees ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY IF NOT EXISTS "Enable all operations for profit_calculations" ON profit_calculations
    FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Enable all operations for custom_fees" ON custom_fees
    FOR ALL USING (true) WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE profit_calculations IS '利润计算表，存储每个询价单的利润计算数据包括运费';
COMMENT ON TABLE custom_fees IS '自定义费用表，存储用户定义的额外费用项';
COMMENT ON COLUMN profit_calculations.freight_fee IS '运费';